### ISSUE TITLE
Migrate to monolingual language packages

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-cym-eng#3]
This pair currently embeds the following monolingual information:

* `apertium-cym-eng.cym.acx`
* `apertium-cym-eng.cym.dix`
* `apertium-cym-eng.cym.tsx`
* `apertium-cym-eng.eng.acx`
* `apertium-cym-eng.eng.dix`
* `apertium-cym-eng.eng.tsx`
* `apertium-cym-eng.en-poly.dix`
* `apertium-cym-eng.orth-cym.dix`
* `apertium-cym-eng.post-cym.dix`
* `apertium-cym-eng.post-eng.dix`
* `apertium-cym-eng.pre-cym.t1x`
* `cym-eng.prob`
* `eng-cym.prob`

These files should be imported from `apertium-cym` and `apertium-eng`. After doing this, `testvoc` will need to be done. It is recommended to do this on a branch and then merge to master after it is finished and the testvoc results are as good or better.

**Comment by sushain97** [comment]
Last sentence: *are as :)

On Mar 9, 2018 6:06 PM, "Francis Tyers" <notifications@github.com> wrote:

This pair currently embeds the following monolingual information:

   - apertium-cym-eng.cym.acx
   - apertium-cym-eng.cym.dix
   - apertium-cym-eng.cym.tsx
   - apertium-cym-eng.eng.acx
   - apertium-cym-eng.eng.dix
   - apertium-cym-eng.eng.tsx
   - apertium-cym-eng.en-poly.dix
   - apertium-cym-eng.orth-cym.dix
   - apertium-cym-eng.post-cym.dix
   - apertium-cym-eng.post-eng.dix
   - apertium-cym-eng.pre-cym.t1x
   - cym-eng.prob
   - eng-cym.prob

These files should be imported from apertium-cym and apertium-eng. After
doing this, testvoc will need to be done. It is recommended to do this on a
branch and then merge to master after it is finished and the testvoc
results as as good or better.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/apertium/apertium-cym-eng/issues/3>, or mute the thread

**Comment by ftyers** [comment]
@sushain97 fixed.
